// Package migrations provides goose migrations.
package migrations

import (
	"github.com/JohnGomes/Go-Modular-Monolith/ms/example/internal/app"
	"github.com/JohnGomes/Go-Modular-Monolith/pkg/def"
	goosepkg "github.com/powerman/goose/v2"
)

//nolint:gochecknoglobals // Force code generated by `goose create` to use instance.
var goose = def.NewGoose(app.ServiceName)

// Goose returns goose instance with Go migrations defined in the package.
func Goose() *goosepkg.Instance { return goose }
